/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app-footer.vue')['default']
    AppHeader: typeof import('./components/app-header.vue')['default']
    Game: typeof import('./components/game.vue')['default']
    GameScreen: typeof import('./components/game-screen.vue')['default']
    LoadGame: typeof import('./components/load-game.vue')['default']
    MainMenu: typeof import('./components/main-menu.vue')['default']
    NewGame: typeof import('./components/new-game.vue')['default']
    Options: typeof import('./components/options.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
