# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.103
    - name: install dependencies
      run: dotnet add package Microsoft.EntityFrameworkCore.Design --version 8.0.3 && \
           dotnet add package Microsoft.EntityFrameworkCore.InMemory --version 8.0.3 && \
           dotnet add package Microsoft.EntityFrameworkCore.SqLite --version 8.0.3 && \
           dotnet add package Moq --version 4.20.70
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
